language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
script: 
  - python setup.py install
  - nosetests --with-coverage --cover-package=bragly

